// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmifyfFywDpNL7nMwqyqZOltGZur54_zw',
    appId: '1:644181578684:web:a5c193d4f79f215b1b51b9',
    messagingSenderId: '644181578684',
    projectId: 'chatapp-d9956',
    authDomain: 'chatapp-d9956.firebaseapp.com',
    storageBucket: 'chatapp-d9956.appspot.com',
    measurementId: 'G-VWWS6MZXYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8kQWx3gpUpBqQrntAOC8fiOxX5QGxs4E',
    appId: '1:644181578684:android:319892dce49101f71b51b9',
    messagingSenderId: '644181578684',
    projectId: 'chatapp-d9956',
    storageBucket: 'chatapp-d9956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYyS3yOX07TVWR4btFAeThP8ab7ZmwBI',
    appId: '1:644181578684:ios:91451536f18c80111b51b9',
    messagingSenderId: '644181578684',
    projectId: 'chatapp-d9956',
    storageBucket: 'chatapp-d9956.appspot.com',
    iosClientId: '644181578684-l7hjcdfnomqdbppjdcj9u5rvh3ubeehi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYyS3yOX07TVWR4btFAeThP8ab7ZmwBI',
    appId: '1:644181578684:ios:91451536f18c80111b51b9',
    messagingSenderId: '644181578684',
    projectId: 'chatapp-d9956',
    storageBucket: 'chatapp-d9956.appspot.com',
    iosClientId: '644181578684-l7hjcdfnomqdbppjdcj9u5rvh3ubeehi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
